name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["3.10", "3.11"]

    name: Test with Python ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install --upgrade --no-cache-dir -e ".[dev]"

      - name: Run tests
        run: |
            make test
